        /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;
import bean.LvbCliente;
import dao.ClienteDAO;
import javax.swing.JOptionPane;
import tools.Util;
/**
 *
 * @author u04893768190
 */
public class JDlgClientes extends javax.swing.JDialog {
private boolean incluir;
private boolean pesquisar;
    /**
     * Creates new form JDlgUsuarios
     */
    public JDlgClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de clientes");
        setLocationRelativeTo(null);
        Util.habilitar(false , jBtnConcluir, jBtnExcluir, jBtnCancelar, jFmtCpf, jFmtDataNasc, jCboEstadoCivil, jTxtObservações,jCboSexo,jTxtEmail,jTxtStatus,
                 jTxtPreferencias, jTxtId, jTxtIdade, jTxtProfissao, jFmtRg, jFmtNumero, jTxtNome, jTxtId, jTxtObservações,
                  jFmtDataCadastro);
         
   
        Util.habilitar(true ,jBtnAlterar, jBtnIncluir, jBtnPesquisar);
        jBtnIncluir.requestFocus();
    }
  
    public LvbCliente viewBean(){
        LvbCliente lvbCliente = new LvbCliente();
        //LvbCliente.setLvbIdCliente(Util.strToInt(jTxtId.getText()));
            int codigo = Util.strToInt(jTxtId.getText());
            lvbCliente.setLvbIdCliente(codigo);
            lvbCliente.setLvbCpf(jFmtCpf.getText());
            lvbCliente.setLvbDataNascimento(Util.strToDate(jFmtDataNasc.getText()));
            lvbCliente.setLvbDataCadastro(Util.strToDate(jFmtDataCadastro.getText()));
            lvbCliente.setLvbEmail(jTxtEmail.getText());
            lvbCliente.setLvbEstadoCivill(jCboEstadoCivil.getSelectedIndex());
            lvbCliente.setLvbIdade(jTxtIdade.getText());
            lvbCliente.setLvbNome(jTxtNome.getText());
            lvbCliente.setLvbObservacoes(jTxtObservações.getText());
            lvbCliente.setLvbPrefeciasVeiculos(jTxtPreferencias.getText());
            lvbCliente.setLvbProfissao(jTxtProfissao.getText());
            lvbCliente.setLvbRg(jFmtRg.getText());
            lvbCliente.setLvbSexo(jCboSexo.getSelectedIndex());
            lvbCliente.setLvbStatusCliente(jTxtObservações.getText());
            lvbCliente.setLvbTelefone(jFmtNumero.getText());
            lvbCliente.setLvbStatusCliente(jTxtStatus.getText());
            return lvbCliente;
            }
    public void beanView(LvbCliente lvbCliente){
    
             jTxtId.setText(Util.intToStr(lvbCliente.getLvbIdCliente()));
             jFmtCpf.setText(lvbCliente.getLvbCpf());
             jFmtDataCadastro.setText(Util.dateToStr(lvbCliente.getLvbDataCadastro()));
             jFmtDataNasc.setText(Util.dateToStr(lvbCliente.getLvbDataNascimento()));
             jTxtEmail.setText(lvbCliente.getLvbEmail());
             jCboEstadoCivil.setSelectedIndex(lvbCliente.getLvbEstadoCivill());
             jTxtIdade.setText(lvbCliente.getLvbIdade());
             jTxtNome.setText(lvbCliente.getLvbNome());
             jTxtObservações.setText(lvbCliente.getLvbObservacoes());
             jTxtPreferencias.setText(lvbCliente.getLvbPrefeciasVeiculos());
             jTxtProfissao.setText(lvbCliente.getLvbProfissao());
             jFmtRg.setText(lvbCliente.getLvbRg());
             jCboSexo.setSelectedIndex(lvbCliente.getLvbSexo());
             jTxtObservações.setText(lvbCliente.getLvbStatusCliente());
             jFmtNumero.setText(lvbCliente.getLvbTelefone());
             jTxtStatus.setText(lvbCliente.getLvbStatusCliente());
             
    }

   
         
        
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblDataNascimento = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jBtnCancelar = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jFmtDataNasc = new javax.swing.JFormattedTextField();
        jTxtId = new javax.swing.JTextField();
        jBtnExcluir = new javax.swing.JButton();
        jLblCPF = new javax.swing.JLabel();
        jLblId = new javax.swing.JLabel();
        jBtnConcluir = new javax.swing.JButton();
        jFmtCpf = new javax.swing.JFormattedTextField();
        jLblNome = new javax.swing.JLabel();
        jBtnPesquisar = new javax.swing.JButton();
        jLblProfissao = new javax.swing.JLabel();
        jLblSexo = new javax.swing.JLabel();
        jLblRg = new javax.swing.JLabel();
        jLblPreferencias = new javax.swing.JLabel();
        jLblStatus = new javax.swing.JLabel();
        jLblObservacoes = new javax.swing.JLabel();
        jLblTelefone = new javax.swing.JLabel();
        jFmtDataCadastro = new javax.swing.JFormattedTextField();
        jLblDataCadastro = new javax.swing.JLabel();
        jLblEstadoCivil = new javax.swing.JLabel();
        jTxtProfissao = new javax.swing.JTextField();
        jTxtIdade = new javax.swing.JTextField();
        jLblIdade = new javax.swing.JLabel();
        jBtnAlterar = new javax.swing.JButton();
        jCboEstadoCivil = new javax.swing.JComboBox<>();
        jLblEmail = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jCboSexo = new javax.swing.JComboBox<>();
        jTxtPreferencias = new javax.swing.JTextField();
        jTxtObservações = new javax.swing.JTextField();
        jTxtStatus = new javax.swing.JTextField();
        jFmtNumero = new javax.swing.JFormattedTextField();
        jFmtRg = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblDataNascimento.setText("Data Nascimento");

        jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jBtnCancelar.setText("cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        try {
            jFmtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDataNascActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jLblCPF.setText("CPF");

        jLblId.setText("Id");

        jBtnConcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        jBtnConcluir.setText("confirmar");
        jBtnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConcluirActionPerformed(evt);
            }
        });

        try {
            jFmtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCpfActionPerformed(evt);
            }
        });

        jLblNome.setText("Nome");

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLblProfissao.setText("Profissao");

        jLblSexo.setText("Sexo");

        jLblRg.setText("Rg");

        jLblPreferencias.setText("preferencias");

        jLblStatus.setText("Status");

        jLblObservacoes.setText("observações");

        jLblTelefone.setText("Telefone");

        try {
            jFmtDataCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtDataCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDataCadastroActionPerformed(evt);
            }
        });

        jLblDataCadastro.setText("Data Cadastro");

        jLblEstadoCivil.setText("Estado Civil");

        jTxtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIdadeActionPerformed(evt);
            }
        });

        jLblIdade.setText("Idade");

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jBtnAlterar.setText("alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jCboEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Separado", "Divorciado", "Viuvo" }));
        jCboEstadoCivil.setSelectedIndex(-1);

        jLblEmail.setText("Email");

        jCboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homem", "Mulher", "Prefiro nao informar" }));
        jCboSexo.setSelectedIndex(-1);

        jTxtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtStatusActionPerformed(evt);
            }
        });

        try {
            jFmtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFmtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblPreferencias)
                            .addComponent(jTxtPreferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxtObservações, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(187, 187, 187))
                            .addComponent(jLblStatus)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jLblObservacoes))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFmtNumero, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLblProfissao, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblId)
                                            .addComponent(jLblNome)
                                            .addComponent(jLblCPF)
                                            .addComponent(jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblSexo)
                                            .addComponent(jCboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jFmtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLblDataNascimento))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLblIdade))
                                        .addGap(11, 11, 11)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLblTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblEmail, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblEstadoCivil))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLblRg))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFmtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFmtRg)))))
                        .addGap(197, 197, 197))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTxtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(198, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblProfissao)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblCPF)
                            .addComponent(jLblSexo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblIdade)
                            .addComponent(jLblDataNascimento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEstadoCivil)
                    .addComponent(jLblDataCadastro)
                    .addComponent(jLblRg))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblEmail)
                .addGap(18, 18, 18)
                .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblObservacoes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblStatus)
                        .addComponent(jLblPreferencias)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtObservações, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPreferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCancelar))
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addComponent(jTxtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(434, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        pesquisar = false;
        Util.habilitar(false , jBtnConcluir, jBtnCancelar, jFmtCpf, jFmtDataNasc, jCboEstadoCivil, jTxtObservações,jCboSexo,jTxtEmail,jTxtStatus,
                 jTxtPreferencias, jTxtId, jTxtIdade, jTxtProfissao, jFmtRg, jFmtNumero, jTxtNome, jTxtId, jTxtObservações,
                  jFmtDataCadastro);
         
   
        Util.habilitar(true , jBtnIncluir, jBtnPesquisar,jBtnAlterar);
        Util.limpar(jFmtDataNasc, jCboEstadoCivil, jTxtObservações,jCboSexo,jTxtEmail,jTxtStatus,
                 jTxtPreferencias, jTxtId, jTxtIdade, jTxtProfissao, jFmtRg, jFmtNumero, jTxtNome, jTxtId, jTxtObservações,
                  jFmtDataCadastro);
jBtnIncluir.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        incluir = true;
        Util.habilitar(true , jBtnConcluir, jBtnCancelar, jFmtCpf, jFmtDataNasc, jCboEstadoCivil, jTxtObservações,jCboSexo,jTxtEmail,jTxtStatus,
                 jTxtPreferencias, jTxtId, jTxtIdade, jTxtProfissao, jFmtRg, jFmtNumero, jTxtNome, jTxtId, jTxtObservações,
                  jFmtDataCadastro);
         
   
        Util.habilitar(false ,jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar);   
        Util.limpar(jFmtDataNasc, jCboEstadoCivil, jTxtObservações,jCboSexo,jTxtEmail,jTxtStatus,
                 jTxtPreferencias, jTxtId, jTxtIdade, jTxtProfissao, jFmtRg, jFmtNumero, jTxtNome, jTxtId, jTxtObservações,
                  jFmtDataCadastro);// TODO add your handling code here:
        jTxtId.requestFocus();
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
       
       if (Util.perguntar("deseja exlcuir o registo?") == true){
        
        ClienteDAO clienteDAO = new ClienteDAO();
        clienteDAO.delete(viewBean());
        }
       
      
           
           Util.habilitar(false , jBtnAlterar, jBtnConcluir, jFmtCpf, jFmtDataNasc, jCboEstadoCivil, jTxtObservações,jCboSexo,jTxtEmail,jTxtStatus,
                 jTxtPreferencias, jTxtId, jTxtIdade, jTxtProfissao, jFmtRg, jFmtNumero, jTxtNome, jTxtId, jTxtObservações,
                  jFmtDataCadastro);
         
   
        Util.habilitar(true , jBtnExcluir, jBtnIncluir, jBtnPesquisar);
        Util.limpar(jFmtCpf, jFmtDataNasc, jCboEstadoCivil, jTxtObservações,jCboSexo,jTxtEmail,
                 jTxtPreferencias, jTxtId, jTxtIdade, jTxtProfissao, jFmtRg, jFmtNumero, jTxtNome, jTxtId, jTxtObservações,
                  jFmtDataCadastro);
        jBtnIncluir.requestFocus();
          
            // TODO add your handling code here:
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConcluirActionPerformed
        // TODO add your handling code here:
        pesquisar = false;
        ClienteDAO clienteDAO = new ClienteDAO();
         if (incluir == true ){
        
        clienteDAO.insert(viewBean());
        
        }else{
        
        clienteDAO.update(viewBean());
        }
        Util.limpar(jBtnConcluir, jBtnCancelar, jFmtDataNasc, jCboEstadoCivil, jTxtObservações,jCboSexo,jTxtEmail,jTxtStatus,
                 jTxtPreferencias, jTxtId, jTxtIdade, jTxtProfissao, jFmtRg, jFmtNumero, jTxtNome, jTxtId, jTxtObservações,
                  jFmtDataCadastro);
        Util.habilitar(false ,jBtnConcluir, jBtnCancelar, jFmtCpf, jFmtDataNasc, jCboEstadoCivil, jTxtObservações,jCboSexo,jTxtEmail,jTxtStatus,
                 jTxtPreferencias, jTxtId, jTxtIdade, jTxtProfissao, jFmtRg, jFmtNumero, jTxtNome, jTxtId, jTxtObservações,
                  jFmtDataCadastro);
                 Util.habilitar(true , jBtnExcluir, jBtnIncluir, jBtnPesquisar); 
                 jBtnIncluir.requestFocus();
    }//GEN-LAST:event_jBtnConcluirActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
   pesquisar = true;
        JDlgPesquisarClientes jDlgPesquisarCliente = new JDlgPesquisarClientes(null, true);
        jDlgPesquisarCliente.setTelaAnterior(this);
        jDlgPesquisarCliente.setVisible(true);
        
        Util.habilitar(false , jBtnConcluir, jBtnCancelar, jFmtDataNasc, jCboEstadoCivil, jTxtObservações,jCboSexo,jTxtEmail,jTxtStatus,
                 jTxtPreferencias, jTxtId, jTxtIdade, jTxtProfissao, jFmtRg, jFmtNumero, jTxtNome, jTxtId, jTxtObservações,
                  jFmtDataCadastro);
         
   
        Util.habilitar(true ,jBtnAlterar, jBtnExcluir, jBtnPesquisar);
        jBtnAlterar.requestFocus();
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jFmtDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtDataNascActionPerformed

    private void jFmtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCpfActionPerformed

    private void jFmtDataCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDataCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtDataCadastroActionPerformed

    private void jTxtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIdadeActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
     incluir = false;
     if(pesquisar == true){
        Util.habilitar(true , jFmtCpf,jBtnConcluir, jBtnCancelar, jFmtDataNasc, jCboEstadoCivil, jTxtObservações,jCboSexo,jTxtEmail,jTxtStatus,
                 jTxtPreferencias, jTxtId, jTxtIdade, jTxtProfissao, jFmtRg, jFmtNumero, jTxtNome, jTxtId, jTxtObservações,
                  jFmtDataCadastro);
         
   
        Util.habilitar(false , jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar);  
        jTxtNome.requestFocus();
     
     }else { JOptionPane.showMessageDialog(this, 
                "Pesquise um bean", 
                "Erro de pesquisa", 
                JOptionPane.ERROR_MESSAGE);
     jBtnIncluir.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jTxtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgClientes dialog = new JDlgClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConcluir;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCboEstadoCivil;
    private javax.swing.JComboBox<String> jCboSexo;
    private javax.swing.JFormattedTextField jFmtCpf;
    private javax.swing.JFormattedTextField jFmtDataCadastro;
    private javax.swing.JFormattedTextField jFmtDataNasc;
    private javax.swing.JFormattedTextField jFmtNumero;
    private javax.swing.JFormattedTextField jFmtRg;
    private javax.swing.JLabel jLblCPF;
    private javax.swing.JLabel jLblDataCadastro;
    private javax.swing.JLabel jLblDataNascimento;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblEstadoCivil;
    private javax.swing.JLabel jLblId;
    private javax.swing.JLabel jLblIdade;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblObservacoes;
    private javax.swing.JLabel jLblPreferencias;
    private javax.swing.JLabel jLblProfissao;
    private javax.swing.JLabel jLblRg;
    private javax.swing.JLabel jLblSexo;
    private javax.swing.JLabel jLblStatus;
    private javax.swing.JLabel jLblTelefone;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtIdade;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtObservações;
    private javax.swing.JTextField jTxtPreferencias;
    private javax.swing.JTextField jTxtProfissao;
    private javax.swing.JTextField jTxtStatus;
    // End of variables declaration//GEN-END:variables
}
