/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.LvbCliente;
import bean.LvbUsuarios;
import bean.LvbVenda;
import bean.LvbVendaVeiculos;
import bean.LvbVendedor;
import dao.ClienteDAO;
import dao.UsuariosDAO;
import dao.VendaDAO;
import dao.VendaVeiculosDAO;
import dao.VendedorDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import tools.Util;

/**
 *
 * @author lucas
 */
public class JDlgVenda extends javax.swing.JDialog {

    ControllerVendaVeiculos controllerVendaVeiculos;
    private boolean incluir;
private boolean pesquisar;
    JDlgVenda jDlgVenda;

    public void setTelaAnterior(JDlgVenda jDlgVenda) {
        this.jDlgVenda = jDlgVenda;
    }

    /**
     * Creates new form JDlgVenda
     */
    public JDlgVenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Vendas Veiculos");
        Util.habilitar(false, jTxtCodigo, jTable1, jFmtData, jCboCliente, jCboVendedor, jTxtTotal, jBtnAlterar,jBtnExcluir,
                jBtnCancelar, jBtnConfirmar, jBtnAlterarProd, jBtnExcluirProd, jBtnIncluirProd);
        Util.habilitar(true, jBtnIncluir, jBtnPesquisar,jBtnAlterar);
        jBtnIncluir.requestFocus();
        jCboCliente.removeAllItems();
        ClienteDAO clientesDAO = new ClienteDAO();
        List lista = (List) clientesDAO.listAll();
        for (Object object : lista) {
            jCboCliente.addItem((LvbCliente) object);

        }
        jCboVendedor.removeAllItems();
        VendedorDAO vendedorDAO = new VendedorDAO();
        List listaVend = (List) vendedorDAO.listAll();
        for (Object object : listaVend) {
            jCboVendedor.addItem((LvbVendedor) object);
        }

        controllerVendaVeiculos = new ControllerVendaVeiculos();
        controllerVendaVeiculos.setList(new ArrayList());
        jTable1.setModel(controllerVendaVeiculos);
    }

    public LvbVenda viewBean() {
        LvbVenda venda = new LvbVenda();
        venda.setLvbCliente((LvbCliente) jCboCliente.getSelectedItem());
        venda.setLvbIdVenda(Util.strToInt(jTxtCodigo.getText()));
        venda.setLvbTotal(Util.strToDouble(jTxtTotal.getText()));
        venda.setLvbVendedor((LvbVendedor) jCboVendedor.getSelectedItem());
        venda.setLvbDataVenda(Util.strToDate(jFmtData.getText()));

        return venda;
    }

    public void beanView(LvbVenda venda) {
        jTxtCodigo.setText(Util.intToStr(venda.getLvbIdVenda()));
        jFmtData.setText(Util.dateToStr(venda.getLvbDataVenda()));
        jCboCliente.setSelectedItem(venda.getLvbCliente());
        jCboVendedor.setSelectedItem(venda.getLvbVendedor());
        jFmtData.setText(Util.dateToStr(venda.getLvbDataVenda()));
        jTxtTotal.setText(Util.doubleToStr(venda.getLvbTotal()));
        VendaVeiculosDAO pedidosProdutosDAO = new VendaVeiculosDAO();
        List lista = (List) pedidosProdutosDAO.listVenda(venda);
        controllerVendaVeiculos.setList(lista);

    }

    public JTable getjTable1() {
        return jTable1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLblCodifo = new javax.swing.JLabel();
        jLblData = new javax.swing.JLabel();
        jLblCliente = new javax.swing.JLabel();
        jLblVendedor = new javax.swing.JLabel();
        jLblTotal = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jFmtData = new javax.swing.JFormattedTextField();
        jCboCliente = new javax.swing.JComboBox<LvbCliente>();
        jCboVendedor = new javax.swing.JComboBox<LvbVendedor>();
        jTxtTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnIncluirProd = new javax.swing.JButton();
        jBtnAlterarProd = new javax.swing.JButton();
        jBtnExcluirProd = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblCodifo.setText("Codigo");

        jLblData.setText("Data");

        jLblCliente.setText("Cliente");

        jLblVendedor.setText("Vendedor");

        jLblTotal.setText("Total");

        jFmtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDataActionPerformed(evt);
            }
        });

        jCboVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboVendedorActionPerformed(evt);
            }
        });

        jTxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTotalActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnIncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirProdActionPerformed(evt);
            }
        });

        jBtnAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarProdActionPerformed(evt);
            }
        });

        jBtnExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCodifo)
                            .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblData)
                                .addGap(69, 69, 69))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblCliente)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jCboCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblVendedor)
                            .addComponent(jCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblTotal)
                            .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnAlterarProd)
                            .addComponent(jBtnIncluirProd)
                            .addComponent(jBtnExcluirProd))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCodifo)
                    .addComponent(jLblData)
                    .addComponent(jLblCliente)
                    .addComponent(jLblVendedor)
                    .addComponent(jLblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jBtnIncluirProd)
                        .addGap(7, 7, 7)
                        .addComponent(jBtnAlterarProd)
                        .addGap(4, 4, 4)
                        .addComponent(jBtnExcluirProd)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jBtnIncluir))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFmtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtDataActionPerformed

    private void jCboVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboVendedorActionPerformed

    private void jTxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTotalActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        pesquisar = true;
        JDlgPesquisarVenda jDlgPesquisarVenda = new JDlgPesquisarVenda(null, true);
        jDlgPesquisarVenda.setTelaAnterior(this);
        jDlgPesquisarVenda.setVisible(true);
        Util.habilitar(true, jBtnExcluir, jBtnAlterar);
        Util.habilitar(false, jFmtData, jCboCliente, jCboVendedor, jTxtTotal);
        jBtnAlterar.requestFocus();
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        incluir = true;
        Util.habilitar(true, jTxtCodigo, jTable1, jFmtData, jCboCliente, jCboVendedor, jTxtTotal, jBtnAlterar,
                jBtnCancelar, jBtnConfirmar, jBtnAlterarProd, jBtnExcluirProd, jBtnIncluirProd, jBtnAlterar);
        Util.habilitar(false, jBtnIncluir, jBtnPesquisar, jBtnExcluir, jBtnAlterar);
        Util.limpar(jTxtCodigo, jFmtData, jCboCliente, jCboVendedor, jTxtTotal);
        jTxtCodigo.requestFocus();
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        incluir = false;
        if(pesquisar == true){
        Util.habilitar(true, jTxtCodigo, jTable1, jFmtData, jCboCliente, jCboVendedor, jTxtTotal, jBtnAlterar,
                jBtnCancelar, jBtnConfirmar, jBtnAlterarProd, jBtnExcluirProd, jBtnIncluirProd, jBtnAlterar);

        Util.habilitar(false, jTxtCodigo, jBtnIncluir, jBtnPesquisar, jBtnExcluir, jBtnAlterar);
         
        jFmtData.requestFocus();
        }else{
        
        JOptionPane.showMessageDialog(this, 
                "Pesquise um bean", 
                "Erro de pesquisa", 
                JOptionPane.ERROR_MESSAGE);
        jBtnIncluir.requestFocus();
        }
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (Util.perguntar("Deseja excluir ?") == true) {
           
            VendaDAO vendaDAO = new VendaDAO();
            VendaVeiculosDAO vendaVeiculosDAO = new VendaVeiculosDAO();
            for (int ind = 0; ind < jTable1.getRowCount(); ind++) {
                LvbVendaVeiculos vendaVeiculos = controllerVendaVeiculos.getBean(ind);
                vendaVeiculosDAO.delete(vendaVeiculos);
            }
            vendaDAO.delete(viewBean());
        
        Util.limpar(jTxtCodigo, jFmtData, jCboCliente, jCboVendedor, jTxtTotal);
        controllerVendaVeiculos.setList(new ArrayList());
        
             }jBtnIncluir.requestFocus();
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        VendaDAO vendaDAO = new VendaDAO();
        VendaVeiculosDAO vendasProdutosDAO = new VendaVeiculosDAO();
        LvbVenda lvbVenda = viewBean();
        if (incluir == true) {
            vendaDAO.insert(lvbVenda);
            for (int ind = 0; ind < jTable1.getRowCount(); ind++) {
                LvbVendaVeiculos vendaVeiculos = controllerVendaVeiculos.getBean(ind);
                vendaVeiculos.setLvbVenda(lvbVenda);
                vendasProdutosDAO.insert(vendaVeiculos);
            }
        } else {
            vendaDAO.update(lvbVenda);
            //excluo todos os pedidos produtos do pedido
            vendasProdutosDAO.deleteProdutos(lvbVenda);
            //incluo os pedidos produtos
            for (int ind = 0; ind < jTable1.getRowCount(); ind++) {
                LvbVendaVeiculos VendaVeiculos = controllerVendaVeiculos.getBean(ind);
                VendaVeiculos.setLvbVenda(lvbVenda);
                vendasProdutosDAO.insert(VendaVeiculos);
            }
        }

        Util.habilitar(false, jTxtCodigo, jTable1, jFmtData, jCboCliente, jCboVendedor, jTxtTotal, jBtnCancelar, jBtnConfirmar, jBtnAlterarProd, jBtnExcluirProd, jBtnIncluirProd);
        Util.habilitar(true, jBtnIncluir, jBtnPesquisar,jBtnAlterar);
        Util.limpar(jTxtCodigo, jFmtData, jCboCliente, jCboVendedor, jTxtTotal);
        controllerVendaVeiculos.setList(new ArrayList());
        jBtnIncluir.requestFocus();

    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        pesquisar = false;
        Util.habilitar(false, jTxtCodigo, jTable1,jFmtData, jCboCliente, jCboVendedor, jTxtTotal, jBtnAlterar, jBtnCancelar, jBtnConfirmar,jBtnAlterarProd,jBtnExcluirProd,jBtnIncluirProd);
        Util.habilitar(true, jBtnIncluir, jBtnPesquisar, jBtnExcluir, jBtnAlterar);
        Util.limpar(jTxtCodigo, jFmtData, jCboCliente, jCboVendedor, jTxtTotal,jTable1);
        jBtnIncluir.requestFocus();

    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnIncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirProdActionPerformed
        // TODO add your handling code here:
   
        JDlgVendaVeiculos jDlgVendaVeiculos = new JDlgVendaVeiculos(null, true);
        jDlgVendaVeiculos.setTelaAnterior(this,null);
        jDlgVendaVeiculos.setVisible(true);
    }//GEN-LAST:event_jBtnIncluirProdActionPerformed

    private void jBtnAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarProdActionPerformed
        // TODO add your handling code here
        if (jTable1.getSelectedRow() == -1) {
            Util.mensagem("Precisa selecionar uma linha!");
        }
        JDlgVendaVeiculos jDlgVendaVeiculos = new JDlgVendaVeiculos(null, true);
        LvbVendaVeiculos vendaVeiculos = controllerVendaVeiculos.getBean(jTable1.getSelectedRow());
        jDlgVendaVeiculos.setTelaAnterior(this,vendaVeiculos);
        jDlgVendaVeiculos.setVisible(true);
    }//GEN-LAST:event_jBtnAlterarProdActionPerformed

    private void jBtnExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirProdActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() == -1) {
            Util.mensagem("Precisa selecionar uma linha!");
        } else {
            if (Util.perguntar("Deseja excluir o produto ?") == true) {
                controllerVendaVeiculos.removeBean(jTable1.getSelectedRow());
                // ADICIONA AQUI
            }
        }


    }//GEN-LAST:event_jBtnExcluirProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVenda dialog = new JDlgVenda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnAlterarProd;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnExcluirProd;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnIncluirProd;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<LvbCliente> jCboCliente;
    private javax.swing.JComboBox<LvbVendedor> jCboVendedor;
    private javax.swing.JFormattedTextField jFmtData;
    private javax.swing.JLabel jLblCliente;
    private javax.swing.JLabel jLblCodifo;
    private javax.swing.JLabel jLblData;
    private javax.swing.JLabel jLblTotal;
    private javax.swing.JLabel jLblVendedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
}
