        /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.LvbVeiculos;
import dao.VeiculosDAO;
import javax.swing.JOptionPane;
import tools.Util;

/**
 *
 * @author u04893768190
 */
public class JDlgVeiculos extends javax.swing.JDialog {
private boolean incluir;
private boolean pesquisar;
    /**
     * Creates new form JDlgUsuarios
     */
    public JDlgVeiculos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Veiculos");
        setLocationRelativeTo(null);
         Util.habilitar(false , jBtnConcluir, jBtnCancelar,jFmtAno, jTxtModificacoes,  jTxtMarca, jBtnExcluir,
                jTxtModelo, jTxtId, jTxtCor, jTxtValor);
         
   
        Util.habilitar(true ,jBtnAlterar, jBtnIncluir, jBtnPesquisar);
        jBtnIncluir.requestFocus();
    }
    public LvbVeiculos viewBean(){
    LvbVeiculos lvbVeiculos = new LvbVeiculos();
    
    int codigo = Util.strToInt(jTxtId.getText());
    lvbVeiculos.setLvbIdVeiculos(codigo);
    lvbVeiculos.setLvbAno(Util.strToDate(jFmtAno.getText()));
    lvbVeiculos.setLvbCor(jTxtCor.getText());
    lvbVeiculos.setLvbMarca(jTxtMarca.getText());
    lvbVeiculos.setLvbModelo(jTxtModelo.getText());
    lvbVeiculos.setLvbModificacao(jTxtModificacoes.getText());
    lvbVeiculos.setLvbValor(Util.strToDouble(jTxtValor.getText()));
    return lvbVeiculos;
                
    }
    public void beanView(LvbVeiculos lvbVeiculos){
    jTxtId.setText(Util.intToStr(lvbVeiculos.getLvbIdVeiculos()));
    jFmtAno.setText(Util.dateToStr(lvbVeiculos.getLvbAno()));
    jTxtCor.setText(lvbVeiculos.getLvbCor());
    jTxtMarca.setText(lvbVeiculos.getLvbMarca());
    jTxtModelo.setText(lvbVeiculos.getLvbModelo());
    jTxtModificacoes.setText(lvbVeiculos.getLvbModificacao());
    jTxtValor.setText(Util.doubleToStr(lvbVeiculos.getLvbValor()));
    
    
    
    }
         
   
      
    

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblModificacoes = new javax.swing.JLabel();
        jTxtModelo = new javax.swing.JTextField();
        jBtnCancelar = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jTxtModificacoes = new javax.swing.JFormattedTextField();
        jBtnAlterar = new javax.swing.JButton();
        jTxtId = new javax.swing.JTextField();
        jBtnExcluir = new javax.swing.JButton();
        jLblAno = new javax.swing.JLabel();
        jLblModelo = new javax.swing.JLabel();
        jBtnConcluir = new javax.swing.JButton();
        jFmtAno = new javax.swing.JFormattedTextField();
        jLblId = new javax.swing.JLabel();
        jBtnPesquisar = new javax.swing.JButton();
        jLblMarca = new javax.swing.JLabel();
        jLblCor = new javax.swing.JLabel();
        jTxtCor = new javax.swing.JTextField();
        jTxtMarca = new javax.swing.JTextField();
        jTxtValor = new javax.swing.JTextField();
        jLblValor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblModificacoes.setText("Modificacoes");

        jTxtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtModeloActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit_1.png"))); // NOI18N
        jBtnCancelar.setText("cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jTxtModificacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtModificacoesActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        jBtnExcluir.setText("excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jLblAno.setText("Ano");

        jLblModelo.setText("Modelo");

        jBtnConcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConcluir.setText("confirmar");
        jBtnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConcluirActionPerformed(evt);
            }
        });

        try {
            jFmtAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLblId.setText("Id");

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLblMarca.setText("Marca");

        jLblCor.setText("Cor");

        jTxtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtValorActionPerformed(evt);
            }
        });

        jLblValor.setText("Valor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblMarca)
                        .addGap(221, 221, 221)
                        .addComponent(jLblAno))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblId)
                            .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLblModificacoes)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxtModificacoes, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLblCor)
                                .addComponent(jTxtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLblValor)
                                .addComponent(jFmtAno, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(jTxtValor)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblModelo)
                    .addComponent(jLblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblMarca)
                    .addComponent(jLblAno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCor)
                    .addComponent(jLblValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLblModificacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtModificacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCancelar))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtModeloActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        pesquisar=false;        
        
        
        Util.habilitar(false , jBtnConcluir, jBtnCancelar,jFmtAno, jTxtModificacoes,  jTxtMarca,
                jTxtModelo, jTxtId, jTxtCor, jTxtValor);
         
   
        Util.habilitar(true ,jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar);     
        jBtnIncluir.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
         incluir = true;
        Util.habilitar(true , jBtnConcluir, jBtnCancelar,jFmtAno, jTxtModificacoes,  jTxtMarca,
                jTxtModelo, jTxtId, jTxtCor, jTxtValor);
         
   
        Util.habilitar(false ,jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar);
        Util.limpar(jFmtAno, jTxtModificacoes,  jTxtMarca,
                jTxtModelo, jTxtId, jTxtCor, jTxtValor);
        jTxtId.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
                if(Util.perguntar("Deseja Excluir?")== true){
                    VeiculosDAO veiculosDAO = new VeiculosDAO();
                    veiculosDAO.delete(viewBean());
           
        
        
        Util.limpar(jFmtAno, jTxtModificacoes,  jTxtMarca,
                jTxtModelo, jTxtId, jTxtCor, jTxtValor);
         Util.habilitar(false , jBtnConcluir, jBtnCancelar,jFmtAno, jTxtModificacoes,  jTxtMarca,
                jTxtModelo, jTxtId, jTxtCor, jTxtValor);
         
   
        Util.habilitar(true ,jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar);
       
      }
          
           Util.limpar(jFmtAno, jTxtModificacoes,  jTxtMarca,
                jTxtModelo, jTxtId, jTxtCor, jTxtValor);
            Util.habilitar(false , jBtnConcluir, jBtnCancelar,jFmtAno, jTxtModificacoes,  jTxtMarca,
                jTxtModelo, jTxtId, jTxtCor, jTxtValor);
         
   
        Util.habilitar(true ,jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar);
        jBtnIncluir.requestFocus();
          
          // TODO add your handling code here:
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConcluirActionPerformed
        VeiculosDAO veiculosDAO = new VeiculosDAO();
        if(incluir == true){
            
            
            veiculosDAO.insert(viewBean());
        }else{
        
            veiculosDAO.update(viewBean());
        
        }  
        
        
        Util.limpar(jFmtAno, jTxtModificacoes,  jTxtMarca,
                jTxtModelo, jTxtId, jTxtCor, jTxtValor);
         Util.habilitar(false , jBtnConcluir, jBtnCancelar,jFmtAno, jTxtModificacoes,  jTxtMarca,
                jTxtModelo, jTxtId, jTxtCor, jTxtValor);
         
   
        Util.habilitar(true , jBtnExcluir, jBtnIncluir, jBtnPesquisar); 
        jBtnIncluir.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnConcluirActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        pesquisar = true;
            JDlgPesquisarVeiculos jDlgPesquisarVeiculo = new JDlgPesquisarVeiculos(null,true);
            jDlgPesquisarVeiculo.setTelaAnterior(this);
            jDlgPesquisarVeiculo.setVisible(true);
            
       
        Util.habilitar(false , jBtnConcluir, jBtnCancelar,jFmtAno, jTxtModificacoes,  jTxtMarca,
                jTxtModelo, jTxtId, jTxtCor, jTxtValor);
         
   
        Util.habilitar(true ,jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar);
        
        
        jBtnAlterar.requestFocus();
           // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jTxtModificacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtModificacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtModificacoesActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        incluir = false;
        if(pesquisar == true){
        Util.habilitar(true , jBtnConcluir, jBtnCancelar,jFmtAno, jTxtModificacoes,  jTxtMarca,
                jTxtModelo, jTxtId, jTxtCor, jTxtValor);
         
   
        Util.habilitar(false ,jTxtId,jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar); 
        jTxtModelo.requestFocus();
        }else  {
            JOptionPane.showMessageDialog(this, 
                "Pesquise um bean", 
                "Erro de pesquisa", 
                JOptionPane.ERROR_MESSAGE);
            jBtnIncluir.requestFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jTxtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVeiculos dialog = new JDlgVeiculos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConcluir;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JFormattedTextField jFmtAno;
    private javax.swing.JLabel jLblAno;
    private javax.swing.JLabel jLblCor;
    private javax.swing.JLabel jLblId;
    private javax.swing.JLabel jLblMarca;
    private javax.swing.JLabel jLblModelo;
    private javax.swing.JLabel jLblModificacoes;
    private javax.swing.JLabel jLblValor;
    private javax.swing.JTextField jTxtCor;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtMarca;
    private javax.swing.JTextField jTxtModelo;
    private javax.swing.JFormattedTextField jTxtModificacoes;
    private javax.swing.JTextField jTxtValor;
    // End of variables declaration//GEN-END:variables
}
