package bean;
// Generated 09/12/2025 15:44:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LvbCliente generated by hbm2java
 */
@Entity
@Table(name="lvb_cliente"
    ,catalog="db_lucas_boeira"
)
public class LvbCliente  implements java.io.Serializable {


     private int lvbIdCliente;
     private String lvbNome;
     private String lvbRg;
     private String lvbIdade;
     private Date lvbDataNascimento;
     private int lvbSexo;
     private String lvbCpf;
     private String lvbEmail;
     private String lvbTelefone;
     private String lvbProfissao;
     private String lvbStatusCliente;
     private String lvbPrefeciasVeiculos;
     private int lvbEstadoCivill;
     private Date lvbDataCadastro;
     private String lvbObservacoes;
     

    public LvbCliente() {
    }

	
    public LvbCliente(String lvbNome, String lvbRg, String lvbIdade, Date lvbDataNascimento, int lvbSexo, String lvbCpf, String lvbEmail, String lvbTelefone, String lvbProfissao, int lvbEstadoCivill) {
        this.lvbNome = lvbNome;
        this.lvbRg = lvbRg;
        this.lvbIdade = lvbIdade;
        this.lvbDataNascimento = lvbDataNascimento;
        this.lvbSexo = lvbSexo;
        this.lvbCpf = lvbCpf;
        this.lvbEmail = lvbEmail;
        this.lvbTelefone = lvbTelefone;
        this.lvbProfissao = lvbProfissao;
        this.lvbEstadoCivill = lvbEstadoCivill;
    }
    public LvbCliente(String lvbNome, String lvbRg, String lvbIdade, Date lvbDataNascimento, int lvbSexo, String lvbCpf, String lvbEmail, String lvbTelefone, String lvbProfissao, String lvbStatusCliente, String lvbPrefeciasVeiculos, int lvbEstadoCivill, Date lvbDataCadastro, String lvbObservacoes, Set lvbVendas) {
       this.lvbNome = lvbNome;
       this.lvbRg = lvbRg;
       this.lvbIdade = lvbIdade;
       this.lvbDataNascimento = lvbDataNascimento;
       this.lvbSexo = lvbSexo;
       this.lvbCpf = lvbCpf;
       this.lvbEmail = lvbEmail;
       this.lvbTelefone = lvbTelefone;
       this.lvbProfissao = lvbProfissao;
       this.lvbStatusCliente = lvbStatusCliente;
       this.lvbPrefeciasVeiculos = lvbPrefeciasVeiculos;
       this.lvbEstadoCivill = lvbEstadoCivill;
       this.lvbDataCadastro = lvbDataCadastro;
       this.lvbObservacoes = lvbObservacoes;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lvb_id_cliente", unique=true, nullable=false)
    public int getLvbIdCliente() {
        return this.lvbIdCliente;
    }
    
    public void setLvbIdCliente(int lvbIdCliente) {
        this.lvbIdCliente = lvbIdCliente;
    }

    
    @Column(name="lvb_nome", nullable=false, length=45)
    public String getLvbNome() {
        return this.lvbNome;
    }
    
    public void setLvbNome(String lvbNome) {
        this.lvbNome = lvbNome;
    }

    
    @Column(name="lvb_rg", nullable=false, length=45)
    public String getLvbRg() {
        return this.lvbRg;
    }
    
    public void setLvbRg(String lvbRg) {
        this.lvbRg = lvbRg;
    }

    
    @Column(name="lvb_idade", nullable=false, length=3)
    public String getLvbIdade() {
        return this.lvbIdade;
    }
    
    public void setLvbIdade(String lvbIdade) {
        this.lvbIdade = lvbIdade;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lvb_dataNascimento", nullable=false, length=10)
    public Date getLvbDataNascimento() {
        return this.lvbDataNascimento;
    }
    
    public void setLvbDataNascimento(Date lvbDataNascimento) {
        this.lvbDataNascimento = lvbDataNascimento;
    }

    
    @Column(name="lvb_sexo", nullable=false)
    public int getLvbSexo() {
        return this.lvbSexo;
    }
    
    public void setLvbSexo(int lvbSexo) {
        this.lvbSexo = lvbSexo;
    }

    
    @Column(name="lvb_cpf", nullable=false, length=14)
    public String getLvbCpf() {
        return this.lvbCpf;
    }
    
    public void setLvbCpf(String lvbCpf) {
        this.lvbCpf = lvbCpf;
    }

    
    @Column(name="lvb_email", nullable=false, length=200)
    public String getLvbEmail() {
        return this.lvbEmail;
    }
    
    public void setLvbEmail(String lvbEmail) {
        this.lvbEmail = lvbEmail;
    }

    
    @Column(name="lvb_telefone", nullable=false, length=20)
    public String getLvbTelefone() {
        return this.lvbTelefone;
    }
    
    public void setLvbTelefone(String lvbTelefone) {
        this.lvbTelefone = lvbTelefone;
    }

    
    @Column(name="lvb_profissao", nullable=false, length=30)
    public String getLvbProfissao() {
        return this.lvbProfissao;
    }
    
    public void setLvbProfissao(String lvbProfissao) {
        this.lvbProfissao = lvbProfissao;
    }

    
    @Column(name="lvb_statusCliente", length=50)
    public String getLvbStatusCliente() {
        return this.lvbStatusCliente;
    }
    
    public void setLvbStatusCliente(String lvbStatusCliente) {
        this.lvbStatusCliente = lvbStatusCliente;
    }

    
    @Column(name="lvb_prefeciasVeiculos", length=60)
    public String getLvbPrefeciasVeiculos() {
        return this.lvbPrefeciasVeiculos;
    }
    
    public void setLvbPrefeciasVeiculos(String lvbPrefeciasVeiculos) {
        this.lvbPrefeciasVeiculos = lvbPrefeciasVeiculos;
    }

    
    @Column(name="lvb_estadoCivill", nullable=false)
    public int getLvbEstadoCivill() {
        return this.lvbEstadoCivill;
    }
    
    public void setLvbEstadoCivill(int lvbEstadoCivill) {
        this.lvbEstadoCivill = lvbEstadoCivill;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lvb_dataCadastro", length=10)
    public Date getLvbDataCadastro() {
        return this.lvbDataCadastro;
    }
    
    public void setLvbDataCadastro(Date lvbDataCadastro) {
        this.lvbDataCadastro = lvbDataCadastro;
    }

    
    @Column(name="lvb_observacoes", length=45)
    public String getLvbObservacoes() {
        return this.lvbObservacoes;
    }
    
    public void setLvbObservacoes(String lvbObservacoes) {
        this.lvbObservacoes = lvbObservacoes;
    }
    @Override
public String toString() {
return this.lvbNome;
}
@Override
public boolean equals(Object object) {
if (object instanceof LvbCliente) {
LvbCliente lvbCliente = (LvbCliente) object;
if (this.getLvbIdCliente()== lvbCliente.getLvbIdCliente()) {
return true;
}
}
return false;
}


}


