package bean;
// Generated 15/10/2025 09:40:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LvbUsuarios generated by hbm2java
 */
@Entity
@Table(name="lvb_usuarios"
    ,catalog="db_lucas_boeira"
)
public class LvbUsuarios  implements java.io.Serializable {


     private Integer lvbIdUsuarios;
     private String lvbNome;
     private String lvbApelido;
     private String lvbCpf;
     private Date lvbDataNascimento;
     private String lvbAtivo;
     private String lvbSenha;
     private Set lvbVendas = new HashSet(0);

    public LvbUsuarios() {
    }

	
    public LvbUsuarios(String lvbNome, String lvbApelido, String lvbCpf, Date lvbDataNascimento, String lvbAtivo, String lvbSenha) {
        this.lvbNome = lvbNome;
        this.lvbApelido = lvbApelido;
        this.lvbCpf = lvbCpf;
        this.lvbDataNascimento = lvbDataNascimento;
        this.lvbAtivo = lvbAtivo;
        this.lvbSenha = lvbSenha;
    }
    public LvbUsuarios(String lvbNome, String lvbApelido, String lvbCpf, Date lvbDataNascimento, String lvbAtivo, String lvbSenha, Set lvbVendas) {
       this.lvbNome = lvbNome;
       this.lvbApelido = lvbApelido;
       this.lvbCpf = lvbCpf;
       this.lvbDataNascimento = lvbDataNascimento;
       this.lvbAtivo = lvbAtivo;
       this.lvbSenha = lvbSenha;
       this.lvbVendas = lvbVendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lvb_id_usuarios", unique=true, nullable=false)
    public Integer getLvbIdUsuarios() {
        return this.lvbIdUsuarios;
    }
    
    public void setLvbIdUsuarios(Integer lvbIdUsuarios) {
        this.lvbIdUsuarios = lvbIdUsuarios;
    }

    
    @Column(name="lvb_nome", nullable=false, length=45)
    public String getLvbNome() {
        return this.lvbNome;
    }
    
    public void setLvbNome(String lvbNome) {
        this.lvbNome = lvbNome;
    }

    
    @Column(name="lvb_apelido", nullable=false, length=45)
    public String getLvbApelido() {
        return this.lvbApelido;
    }
    
    public void setLvbApelido(String lvbApelido) {
        this.lvbApelido = lvbApelido;
    }

    
    @Column(name="lvb_cpf", nullable=false, length=14)
    public String getLvbCpf() {
        return this.lvbCpf;
    }
    
    public void setLvbCpf(String lvbCpf) {
        this.lvbCpf = lvbCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lvb_dataNascimento", nullable=false, length=10)
    public Date getLvbDataNascimento() {
        return this.lvbDataNascimento;
    }
    
    public void setLvbDataNascimento(Date lvbDataNascimento) {
        this.lvbDataNascimento = lvbDataNascimento;
    }

    
    @Column(name="lvb_ativo", nullable=false, length=2)
    public String getLvbAtivo() {
        return this.lvbAtivo;
    }
    
    public void setLvbAtivo(String lvbAtivo) {
        this.lvbAtivo = lvbAtivo;
    }

    
    @Column(name="lvb_senha", nullable=false, length=1)
    public String getLvbSenha() {
        return this.lvbSenha;
    }
    
    public void setLvbSenha(String lvbSenha) {
        this.lvbSenha = lvbSenha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lvbUsuarios")
    public Set getLvbVendas() {
        return this.lvbVendas;
    }
    
    public void setLvbVendas(Set lvbVendas) {
        this.lvbVendas = lvbVendas;
    }




}


