package bean;
// Generated 25/11/2025 17:26:07 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LvbVenda generated by hbm2java
 */
@Entity
@Table(name="lvb_venda"
    ,catalog="db_lucas_boeira"
)
public class LvbVenda  implements java.io.Serializable {


     private int lvbIdVenda;
     private LvbCliente lvbCliente;
     private LvbUsuarios lvbUsuarios;
     private Date lvbDataVenda;
     private double lvbTotal;
     

    public LvbVenda() {
    }

	
    public LvbVenda(LvbCliente lvbCliente, LvbUsuarios lvbUsuarios, Date lvbDataVenda, double lvbTotal) {
        this.lvbCliente = lvbCliente;
        this.lvbUsuarios = lvbUsuarios;
        this.lvbDataVenda = lvbDataVenda;
        this.lvbTotal = lvbTotal;
    }
    public LvbVenda(LvbCliente lvbCliente, LvbUsuarios lvbUsuarios, Date lvbDataVenda, double lvbTotal, Set lvbVendaVeiculoses) {
       this.lvbCliente = lvbCliente;
       this.lvbUsuarios = lvbUsuarios;
       this.lvbDataVenda = lvbDataVenda;
       this.lvbTotal = lvbTotal;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lvb_id_venda", unique=true, nullable=false)
    public int getLvbIdVenda() {
        return this.lvbIdVenda;
    }
    
    public void setLvbIdVenda(int lvbIdVenda) {
        this.lvbIdVenda = lvbIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lvb_cliente_fk", nullable=false)
    public LvbCliente getLvbCliente() {
        return this.lvbCliente;
    }
    
    public void setLvbCliente(LvbCliente lvbCliente) {
        this.lvbCliente = lvbCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lvb_usuarios_fk", nullable=false)
    public LvbUsuarios getLvbUsuarios() {
        return this.lvbUsuarios;
    }
    
    public void setLvbUsuarios(LvbUsuarios lvbUsuarios) {
        this.lvbUsuarios = lvbUsuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lvb_dataVenda", nullable=false, length=10)
    public Date getLvbDataVenda() {
        return this.lvbDataVenda;
    }
    
    public void setLvbDataVenda(Date lvbDataVenda) {
        this.lvbDataVenda = lvbDataVenda;
    }

    
    @Column(name="lvb_total", nullable=false, precision=10)
    public double getLvbTotal() {
        return this.lvbTotal;
    }
    
    public void setLvbTotal(double lvbTotal) {
        this.lvbTotal = lvbTotal;
    }

}


