package bean;
// Generated 09/12/2025 15:44:41 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LvbVeiculos generated by hbm2java
 */
@Entity
@Table(name="lvb_veiculos"
    ,catalog="db_lucas_boeira"
)
public class LvbVeiculos  implements java.io.Serializable {


     private int lvbIdVeiculos;
     private String lvbModelo;
     private Date lvbAno;
     private String lvbMarca;
     private String lvbCor;
     private double lvbValor;
     private String lvbModificacao;
     

    public LvbVeiculos() {
    }

	
    public LvbVeiculos(String lvbModelo, Date lvbAno, String lvbMarca, String lvbCor, double lvbValor, String lvbModificacao) {
        this.lvbModelo = lvbModelo;
        this.lvbAno = lvbAno;
        this.lvbMarca = lvbMarca;
        this.lvbCor = lvbCor;
        this.lvbValor = lvbValor;
        this.lvbModificacao = lvbModificacao;
    }
    public LvbVeiculos(String lvbModelo, Date lvbAno, String lvbMarca, String lvbCor, double lvbValor, String lvbModificacao, Set lvbVendaVeiculoses) {
       this.lvbModelo = lvbModelo;
       this.lvbAno = lvbAno;
       this.lvbMarca = lvbMarca;
       this.lvbCor = lvbCor;
       this.lvbValor = lvbValor;
       this.lvbModificacao = lvbModificacao;
      
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lvb_id_veiculos", unique=true, nullable=false)
    public int getLvbIdVeiculos() {
        return this.lvbIdVeiculos;
    }
    
    public void setLvbIdVeiculos(int lvbIdVeiculos) {
        this.lvbIdVeiculos = lvbIdVeiculos;
    }

    
    @Column(name="lvb_modelo", nullable=false, length=45)
    public String getLvbModelo() {
        return this.lvbModelo;
    }
    
    public void setLvbModelo(String lvbModelo) {
        this.lvbModelo = lvbModelo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lvb_ano", nullable=false, length=10)
    public Date getLvbAno() {
        return this.lvbAno;
    }
    
    public void setLvbAno(Date lvbAno) {
        this.lvbAno = lvbAno;
    }

    
    @Column(name="lvb_marca", nullable=false, length=100)
    public String getLvbMarca() {
        return this.lvbMarca;
    }
    
    public void setLvbMarca(String lvbMarca) {
        this.lvbMarca = lvbMarca;
    }

    
    @Column(name="lvb_cor", nullable=false, length=100)
    public String getLvbCor() {
        return this.lvbCor;
    }
    
    public void setLvbCor(String lvbCor) {
        this.lvbCor = lvbCor;
    }

    
    @Column(name="lvb_valor", nullable=false, precision=11)
    public double getLvbValor() {
        return this.lvbValor;
    }
    
    public void setLvbValor(double lvbValor) {
        this.lvbValor = lvbValor;
    }

    
    @Column(name="lvb_modificacao", nullable=false, length=100)
    public String getLvbModificacao() {
        return this.lvbModificacao;
    }
    
    public void setLvbModificacao(String lvbModificacao) {
        this.lvbModificacao = lvbModificacao;
    }
    @Override
public String toString() {
return this.lvbModelo;
}
@Override
public boolean equals(Object object) {
if (object instanceof LvbVeiculos) {
LvbVeiculos lvbVeiculos = (LvbVeiculos) object;
if (this.getLvbIdVeiculos()== lvbVeiculos.getLvbIdVeiculos()){
return true;
}
}
return false;
}

}


