package bean;
// Generated 25/11/2025 17:26:07 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LvbVendaVeiculos generated by hbm2java
 */
@Entity
@Table(name="lvb_venda_veiculos"
    ,catalog="db_lucas_boeira"
)
public class LvbVendaVeiculos  implements java.io.Serializable {


     private int lvbIdVendaVeiculos;
     private LvbVeiculos lvbVeiculos;
     private LvbVenda lvbVenda;
     private int lvbQuantidade;
     private double lvbValotunitario;

    public LvbVendaVeiculos() {
    }

    public LvbVendaVeiculos(LvbVeiculos lvbVeiculos, LvbVenda lvbVenda, int lvbQuantidade, double lvbValotunitario) {
       this.lvbVeiculos = lvbVeiculos;
       this.lvbVenda = lvbVenda;
       this.lvbQuantidade = lvbQuantidade;
       this.lvbValotunitario = lvbValotunitario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lvb_id_venda_veiculos", unique=true, nullable=false)
    public int getLvbIdVendaVeiculos() {
        return this.lvbIdVendaVeiculos;
    }
    
    public void setLvbIdVendaVeiculos(int lvbIdVendaVeiculos) {
        this.lvbIdVendaVeiculos = lvbIdVendaVeiculos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lvb_veiculos_fk", nullable=false)
    public LvbVeiculos getLvbVeiculos() {
        return this.lvbVeiculos;
    }
    
    public void setLvbVeiculos(LvbVeiculos lvbVeiculos) {
        this.lvbVeiculos = lvbVeiculos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lvb_venda_fk", nullable=false)
    public LvbVenda getLvbVenda() {
        return this.lvbVenda;
    }
    
    public void setLvbVenda(LvbVenda lvbVenda) {
        this.lvbVenda = lvbVenda;
    }

    
    @Column(name="lvb_quantidade", nullable=false)
    public int getLvbQuantidade() {
        return this.lvbQuantidade;
    }
    
    public void setLvbQuantidade(int lvbQuantidade) {
        this.lvbQuantidade = lvbQuantidade;
    }

    
    @Column(name="lvb_valotunitario", nullable=false, precision=10)
    public double getLvbValotunitario() {
        return this.lvbValotunitario;
    }
    
    public void setLvbValotunitario(double lvbValotunitario) {
        this.lvbValotunitario = lvbValotunitario;
    }




}


