package bean;
// Generated 15/10/2025 09:40:55 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LvbVendedor generated by hbm2java
 */
@Entity
@Table(name="lvb_vendedor"
    ,catalog="db_lucas_boeira"
)
public class LvbVendedor  implements java.io.Serializable {


     private Integer lvbIdVendedor;
     private String lvbCpf;
     private String lvbNome;
     private String lvbEndereco;
     private String lvbTelefone;
     private String lvbEmail;
     private BigDecimal lvbSalario;
     private String lvbMetaVendas;
     private String lvbCargo;
     private Set lvbVendas = new HashSet(0);

    public LvbVendedor() {
    }

	
    public LvbVendedor(String lvbCpf, String lvbNome, String lvbEndereco, String lvbTelefone, String lvbEmail, BigDecimal lvbSalario, String lvbMetaVendas, String lvbCargo) {
        this.lvbCpf = lvbCpf;
        this.lvbNome = lvbNome;
        this.lvbEndereco = lvbEndereco;
        this.lvbTelefone = lvbTelefone;
        this.lvbEmail = lvbEmail;
        this.lvbSalario = lvbSalario;
        this.lvbMetaVendas = lvbMetaVendas;
        this.lvbCargo = lvbCargo;
    }
    public LvbVendedor(String lvbCpf, String lvbNome, String lvbEndereco, String lvbTelefone, String lvbEmail, BigDecimal lvbSalario, String lvbMetaVendas, String lvbCargo, Set lvbVendas) {
       this.lvbCpf = lvbCpf;
       this.lvbNome = lvbNome;
       this.lvbEndereco = lvbEndereco;
       this.lvbTelefone = lvbTelefone;
       this.lvbEmail = lvbEmail;
       this.lvbSalario = lvbSalario;
       this.lvbMetaVendas = lvbMetaVendas;
       this.lvbCargo = lvbCargo;
       this.lvbVendas = lvbVendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lvb_id_vendedor", unique=true, nullable=false)
    public Integer getLvbIdVendedor() {
        return this.lvbIdVendedor;
    }
    
    public void setLvbIdVendedor(Integer lvbIdVendedor) {
        this.lvbIdVendedor = lvbIdVendedor;
    }

    
    @Column(name="lvb_cpf", nullable=false, length=14)
    public String getLvbCpf() {
        return this.lvbCpf;
    }
    
    public void setLvbCpf(String lvbCpf) {
        this.lvbCpf = lvbCpf;
    }

    
    @Column(name="lvb_nome", nullable=false, length=50)
    public String getLvbNome() {
        return this.lvbNome;
    }
    
    public void setLvbNome(String lvbNome) {
        this.lvbNome = lvbNome;
    }

    
    @Column(name="lvb_endereco", nullable=false, length=50)
    public String getLvbEndereco() {
        return this.lvbEndereco;
    }
    
    public void setLvbEndereco(String lvbEndereco) {
        this.lvbEndereco = lvbEndereco;
    }

    
    @Column(name="lvb_telefone", nullable=false, length=50)
    public String getLvbTelefone() {
        return this.lvbTelefone;
    }
    
    public void setLvbTelefone(String lvbTelefone) {
        this.lvbTelefone = lvbTelefone;
    }

    
    @Column(name="lvb_email", nullable=false, length=50)
    public String getLvbEmail() {
        return this.lvbEmail;
    }
    
    public void setLvbEmail(String lvbEmail) {
        this.lvbEmail = lvbEmail;
    }

    
    @Column(name="lvb_salario", nullable=false, precision=9)
    public BigDecimal getLvbSalario() {
        return this.lvbSalario;
    }
    
    public void setLvbSalario(BigDecimal lvbSalario) {
        this.lvbSalario = lvbSalario;
    }

    
    @Column(name="lvb_metaVendas", nullable=false, length=50)
    public String getLvbMetaVendas() {
        return this.lvbMetaVendas;
    }
    
    public void setLvbMetaVendas(String lvbMetaVendas) {
        this.lvbMetaVendas = lvbMetaVendas;
    }

    
    @Column(name="lvb_cargo", nullable=false, length=50)
    public String getLvbCargo() {
        return this.lvbCargo;
    }
    
    public void setLvbCargo(String lvbCargo) {
        this.lvbCargo = lvbCargo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lvbVendedor")
    public Set getLvbVendas() {
        return this.lvbVendas;
    }
    
    public void setLvbVendas(Set lvbVendas) {
        this.lvbVendas = lvbVendas;
    }




}


