package bean;
// Generated 15/10/2025 09:40:55 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LvbVeiculos generated by hbm2java
 */
@Entity
@Table(name="lvb_veiculos"
    ,catalog="db_lucas_boeira"
)
public class LvbVeiculos  implements java.io.Serializable {


     private Integer lvbIdVeiculos;
     
     private String lvbModelo;
     private Date lvbAno;
     private String lvbMarca;
     private String lvbCor;
     private BigDecimal lvbValor;
     private String lvbModificacao;
     private Set lvbVendaVeiculoses = new HashSet(0);

    public LvbVeiculos() {
    }

	
    public LvbVeiculos( String lvbModelo, Date lvbAno, String lvbMarca, String lvbCor, BigDecimal lvbValor, String lvbModificacao) {
        
        this.lvbModelo = lvbModelo;
        this.lvbAno = lvbAno;
        this.lvbMarca = lvbMarca;
        this.lvbCor = lvbCor;
        this.lvbValor = lvbValor;
        this.lvbModificacao = lvbModificacao;
    }
    public LvbVeiculos( String lvbModelo, Date lvbAno, String lvbMarca, String lvbCor, BigDecimal lvbValor, String lvbModificacao, Set lvbVendaVeiculoses) {
       this.lvbModelo = lvbModelo;
       this.lvbAno = lvbAno;
       this.lvbMarca = lvbMarca;
       this.lvbCor = lvbCor;
       this.lvbValor = lvbValor;
       this.lvbModificacao = lvbModificacao;
       this.lvbVendaVeiculoses = lvbVendaVeiculoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lvb_id_veiculos", unique=true, nullable=false)
    public Integer getLvbIdVeiculos() {
        return this.lvbIdVeiculos;
    }
    
    public void setLvbIdVeiculos(Integer lvbIdVeiculos) {
        this.lvbIdVeiculos = lvbIdVeiculos;
    }

    
    @Column(name="lvb_modelo", nullable=false, length=45)
    public String getLvbModelo() {
        return this.lvbModelo;
    }
    
    public void setLvbModelo(String lvbModelo) {
        this.lvbModelo = lvbModelo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lvb_ano", nullable=false, length=10)
    public Date getLvbAno() {
        return this.lvbAno;
    }
    
    public void setLvbAno(Date lvbAno) {
        this.lvbAno = lvbAno;
    }

    
    @Column(name="lvb_marca", nullable=false, length=100)
    public String getLvbMarca() {
        return this.lvbMarca;
    }
    
    public void setLvbMarca(String lvbMarca) {
        this.lvbMarca = lvbMarca;
    }

    
    @Column(name="lvb_cor", nullable=false, length=100)
    public String getLvbCor() {
        return this.lvbCor;
    }
    
    public void setLvbCor(String lvbCor) {
        this.lvbCor = lvbCor;
    }

    
    @Column(name="lvb_valor", nullable=false, precision=11)
    public BigDecimal getLvbValor() {
        return this.lvbValor;
    }
    
    public void setLvbValor(BigDecimal lvbValor) {
        this.lvbValor = lvbValor;
    }

    
    @Column(name="lvb_modificacao", nullable=false, length=100)
    public String getLvbModificacao() {
        return this.lvbModificacao;
    }
    
    public void setLvbModificacao(String lvbModificacao) {
        this.lvbModificacao = lvbModificacao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lvbVeiculos")
    public Set getLvbVendaVeiculoses() {
        return this.lvbVendaVeiculoses;
    }
    
    public void setLvbVendaVeiculoses(Set lvbVendaVeiculoses) {
        this.lvbVendaVeiculoses = lvbVendaVeiculoses;
    }




}


